coverage:
  paths:
    - cov.out
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
  hideFooterLink: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
